server:
  port: 8081

spring:
  application:
    name: khmer-code-path-backend
  config:
    import: file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: ${REDIS_HOSTNAME}
      port: ${REDIS_PORT}
  cache:
    type: redis

  ai:
    model:
      embedding:
        text: google-genai

    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          options:
            model: ${GOOGLE_AI_MODEL}
            temperature: 0.7
        embedding:
          api-key: ${GOOGLE_AI_API_KEY}
          text:
            options:
              model: text-embedding-004

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768

jwt:
  secret: ${JWT_SECRET}
  expiration: ${TOKEN_EXPIRATION}
  refresh-expiration: ${REFRESH_TOKEN_EXPIRATION}

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  buket-name: ${MINIO_BUKET_NAME}
